-- CREATE DATABASE testdb;

CREATE TABLE MEMBER (
	memberID VARCHAR(255) NOT NULL PRIMARY KEY,
	password VARCHAR(255) NOT NULL,
	nickname VARCHAR(255) NOT NULL
);

CREATE TABLE BOARD (
	boardID bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	content VARCHAR(255)
);

CREATE TABLE FILE (
	fileID bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
	path VARCHAR(255) NOT NULL,
	originalName VARCHAR(255) NOT NULL,
	UUID VARCHAR(255) NOT NULL
);

-- 관계 테이블 생성

CREATE TABLE WRITE (
	writeID bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
	memberID VARCHAR(255),
	boardID bigint,
	createdDate DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	updatedDate DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	
	FOREIGN KEY (memberID)
	REFERENCES MEMBER(memberID) on UPDATE CASCADE,
	
	FOREIGN KEY (boardID)
	REFERENCES BOARD(boardID) on UPDATE CASCADE
);

CREATE TABLE SAVE (
	boardID bigint,
	fileID bigint,
	
	FOREIGN KEY (boardID)
	REFERENCES BOARD(boardID) on UPDATE CASCADE,
	
	FOREIGN KEY (fileID)
	REFERENCES FILE(fileID) on UPDATE CASCADE
);
